name: Auto Assign Reviewer and Notify

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - master

jobs:
  assign-reviewer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Assign Trey as a reviewer
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=$(jq -r .number < "$GITHUB_EVENT_PATH")
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER/requested_reviewers \
            -d '{"reviewers":["Coontm12"]}'

      - name: Notify Trey
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          PR_NUMBER=$(jq -r .number < "$GITHUB_EVENT_PATH")
          curl -X POST -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            -d "{\"body\": \"@Coontm12, please review this PR & have all tests done by Wednesday @ 12pm EST. \n\n Test Cases: https://docs.google.com/spreadsheets/d/1SZO7zRY_TfFzcovbwJhP9vuIRAO80CurnXgUd_-hVbg/edit?usp=sharing \n\n Dev Site: https://tags-dev.discrescuenetwork.com\"}" \
            "https://api.github.com/repos/${{ github.repository }}/issues/$PR_NUMBER/comments"
